### ISSUE TITLE
Funimation Stream dont work

### ISSUE THREAD

**Issue by Thiago-Heleno** [animeloyalty/animeloyalty#11]
I've enabled headless browser and inserted my credentials, and when I try to stream it keeps saying "The stream could not be opened. If this is a premium stream, check your login and subscription."

![image](https://user-images.githubusercontent.com/64995223/113232762-29cb8f00-9274-11eb-95be-373696d91bdd.png)

**Comment by Deathspike** [comment]
What's the version of AnimeLoyalty? It should be `0.11.3`.
Any lower version won't work due to a change on the Funimation website.

If you're on `0.11.3`, can you tell me from which country you are?
The episode titles are Spanish, so perhaps the Spanish version is slightly different than USA.

**Comment by Thiago-Heleno** [comment]
Hey man, I'm currently using the latest version 0.13.3, and when I try to
stream a free content from Funimation It still doesn't work.

I'm from Brasil, but I tried to use USA vpn and It still didn't work.

Em qui., 1 de abr. de 2021 às 07:32, Deathspike ***@***.***>
escreveu:

**Comment by Deathspike** [comment]
Right. Can you create a clean debug log for me? Please do the following:

1. Close AnimeLoyalty.
2. Go to the folder `C:\Users\[YOURUSERNAME]\animesync\logger` (Windows) or `/home/[YOURUSERNAME]/animesync` (Other).
3. Delete the `.log` files.
4. Start AnimeLoyalty.
5. Remove your credentials.
6. Open the series & episode and wait for the error.
7. Now please attach the new `.log` file to a comment.

Or if you somehow trust me, you can send your existing `.log` file by email to meister.deathspike@outlook.com.
If you changed your credentials, they're in the log, so you might just want to produce a clean log instead!

**Comment by Thiago-Heleno** [comment]
I trust you, I'll send my log file here
See if this log helps you

Em qui., 1 de abr. de 2021 às 08:47, Deathspike ***@***.***>
escreveu:

**Comment by Deathspike** [comment]
I received the log file, thank you. It was extremely useful.
I also double-checked, credentials are never logged, so sharing logs is safe even in public spaces.

Because of the logs you sent, I identified a problem with Brazil & Mexico regions and fixed that.
Try installing `0.11.4` and see if this change solves your problem.

**Comment by Thiago-Heleno** [comment]
I'll try it, thanks

Em qui., 1 de abr. de 2021 às 15:45, Deathspike ***@***.***>
escreveu:
